name: Data Validate
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - run: pip install json-spec
      - run: json validate --schema-file schemas/bridgelist.schema.json --document-file QA/bridgelist.json
      - run: json validate --schema-file schemas/cosmos.chainlist.schema.json --document-file QA/cosmos.chains.json
      - run: json validate --schema-file schemas/evm.chainlist.schema.json --document-file QA/evm.chains.json
      - run: json validate --schema-file schemas/tokenlist.schema.json --document-file QA/tokens.json
     